[package]
name = "gpui-test"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "31ec7ef2ec75b51cb72265ec701ab9b3f5dad8c6" }
rex = { git = "https://github.com/lnay/ReX", branch = "personal", features = [
    "ttfparser-fontparser",
] }
